// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ozxqlgqmwbqdagiqtkzw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96eHFsZ3Ftd2JxZGFnaXF0a3p3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg0MDg0ODYsImV4cCI6MjA4Mzk4NDQ4Nn0.U-LWlU8oqsod2fIp1xR3jctqFFy2qVtB4VOk1p9hawA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});